version: '3.9'
services:
  monolithic:
    container_name: chatting_container
    image: chatting-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    networks:
      - chatting-app

networks:
  chatting-app:
    driver: bridge 